services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"        # Jenkins Web UI
      - "50000:50000"      # Jenkins agent connections
    volumes:
      - jenkins-data:/var/jenkins_home  # Persist Jenkins data
    networks:
      - hostitosti
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.goochem.dev`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=cloudflare"

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      - hostitosti
    ports:
      - "2376:2376"  # Docker API port

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  hostitosti:
    external: true
